/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DiuRouteImport } from './routes/diu'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductSlugRouteImport } from './routes/products.$productSlug'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresStoreSlugRouteImport } from './routes/stores.$storeSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DiuRoute = DiuRouteImport.update({
  id: '/diu',
  path: '/diu',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreSlugRoute = StoresStoreSlugRouteImport.update({
  id: '/stores/$storeSlug',
  path: '/stores/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/diu': typeof DiuRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/diu': typeof DiuRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/products': typeof ProductsIndexRoute
  '/stores': typeof StoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/diu': typeof DiuRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/stores/': typeof StoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/diu'
    | '/new-arrivals'
    | '/offers'
    | '/orders'
    | '/reset-password'
    | '/wishlist'
    | '/products/$productSlug'
    | '/stores/$storeSlug'
    | '/products/'
    | '/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/diu'
    | '/new-arrivals'
    | '/offers'
    | '/orders'
    | '/reset-password'
    | '/wishlist'
    | '/products/$productSlug'
    | '/stores/$storeSlug'
    | '/products'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/diu'
    | '/new-arrivals'
    | '/offers'
    | '/orders'
    | '/reset-password'
    | '/wishlist'
    | '/products/$productSlug'
    | '/stores/$storeSlug'
    | '/products/'
    | '/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  DiuRoute: typeof DiuRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WishlistRoute: typeof WishlistRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  StoresStoreSlugRoute: typeof StoresStoreSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diu': {
      id: '/diu'
      path: '/diu'
      fullPath: '/diu'
      preLoaderRoute: typeof DiuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeSlug': {
      id: '/stores/$storeSlug'
      path: '/stores/$storeSlug'
      fullPath: '/stores/$storeSlug'
      preLoaderRoute: typeof StoresStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  DiuRoute: DiuRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WishlistRoute: WishlistRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  StoresStoreSlugRoute: StoresStoreSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
