/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DiuRouteImport } from './routes/diu'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CampusCampusSlugRouteImport } from './routes/campus.$campusSlug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductSlugRouteImport } from './routes/products.$productSlug'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as SellDashboardRouteImport } from './routes/sell.dashboard'
import { Route as SellLoginRouteImport } from './routes/sell.login'
import { Route as SellRegisterRouteImport } from './routes/sell.register'
import { Route as SellStatusRouteImport } from './routes/sell.status'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as StoresStoreSlugRouteImport } from './routes/stores.$storeSlug'
import { Route as SellDashboardIndexRouteImport } from './routes/sell.dashboard.index'
import { Route as SellDashboardEarningsRouteImport } from './routes/sell.dashboard.earnings'
import { Route as SellDashboardOrdersRouteImport } from './routes/sell.dashboard.orders'
import { Route as SellDashboardReviewsRouteImport } from './routes/sell.dashboard.reviews'
import { Route as SellDashboardStoreRouteImport } from './routes/sell.dashboard.store'
import { Route as SellDashboardProductsIndexRouteImport } from './routes/sell.dashboard.products.index'
import { Route as SellDashboardProductsProductIdRouteImport } from './routes/sell.dashboard.products.$productId'
import { Route as SellDashboardProductsNewRouteImport } from './routes/sell.dashboard.products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DiuRoute = DiuRouteImport.update({
  id: '/diu',
  path: '/diu',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusCampusSlugRoute = CampusCampusSlugRouteImport.update({
  id: '/campus/$campusSlug',
  path: '/campus/$campusSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellDashboardRoute = SellDashboardRouteImport.update({
  id: '/sell/dashboard',
  path: '/sell/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellLoginRoute = SellLoginRouteImport.update({
  id: '/sell/login',
  path: '/sell/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRegisterRoute = SellRegisterRouteImport.update({
  id: '/sell/register',
  path: '/sell/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SellStatusRoute = SellStatusRouteImport.update({
  id: '/sell/status',
  path: '/sell/status',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreSlugRoute = StoresStoreSlugRouteImport.update({
  id: '/stores/$storeSlug',
  path: '/stores/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellDashboardIndexRoute = SellDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellDashboardRoute,
} as any)
const SellDashboardEarningsRoute = SellDashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => SellDashboardRoute,
} as any)
const SellDashboardOrdersRoute = SellDashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellDashboardRoute,
} as any)
const SellDashboardReviewsRoute = SellDashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellDashboardRoute,
} as any)
const SellDashboardStoreRoute = SellDashboardStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => SellDashboardRoute,
} as any)
const SellDashboardProductsIndexRoute =
  SellDashboardProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => SellDashboardRoute,
  } as any)
const SellDashboardProductsProductIdRoute =
  SellDashboardProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => SellDashboardRoute,
  } as any)
const SellDashboardProductsNewRoute =
  SellDashboardProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => SellDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/diu': typeof DiuRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/campus/$campusSlug': typeof CampusCampusSlugRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/sell/dashboard': typeof SellDashboardRouteWithChildren
  '/sell/login': typeof SellLoginRoute
  '/sell/register': typeof SellRegisterRoute
  '/sell/status': typeof SellStatusRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/sell/': typeof SellIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/sell/dashboard/earnings': typeof SellDashboardEarningsRoute
  '/sell/dashboard/orders': typeof SellDashboardOrdersRoute
  '/sell/dashboard/reviews': typeof SellDashboardReviewsRoute
  '/sell/dashboard/store': typeof SellDashboardStoreRoute
  '/sell/dashboard/': typeof SellDashboardIndexRoute
  '/sell/dashboard/products/$productId': typeof SellDashboardProductsProductIdRoute
  '/sell/dashboard/products/new': typeof SellDashboardProductsNewRoute
  '/sell/dashboard/products/': typeof SellDashboardProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/diu': typeof DiuRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/campus/$campusSlug': typeof CampusCampusSlugRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/sell/login': typeof SellLoginRoute
  '/sell/register': typeof SellRegisterRoute
  '/sell/status': typeof SellStatusRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/products': typeof ProductsIndexRoute
  '/sell': typeof SellIndexRoute
  '/stores': typeof StoresIndexRoute
  '/sell/dashboard/earnings': typeof SellDashboardEarningsRoute
  '/sell/dashboard/orders': typeof SellDashboardOrdersRoute
  '/sell/dashboard/reviews': typeof SellDashboardReviewsRoute
  '/sell/dashboard/store': typeof SellDashboardStoreRoute
  '/sell/dashboard': typeof SellDashboardIndexRoute
  '/sell/dashboard/products/$productId': typeof SellDashboardProductsProductIdRoute
  '/sell/dashboard/products/new': typeof SellDashboardProductsNewRoute
  '/sell/dashboard/products': typeof SellDashboardProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/diu': typeof DiuRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/campus/$campusSlug': typeof CampusCampusSlugRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/sell/dashboard': typeof SellDashboardRouteWithChildren
  '/sell/login': typeof SellLoginRoute
  '/sell/register': typeof SellRegisterRoute
  '/sell/status': typeof SellStatusRoute
  '/stores/$storeSlug': typeof StoresStoreSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/sell/': typeof SellIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/sell/dashboard/earnings': typeof SellDashboardEarningsRoute
  '/sell/dashboard/orders': typeof SellDashboardOrdersRoute
  '/sell/dashboard/reviews': typeof SellDashboardReviewsRoute
  '/sell/dashboard/store': typeof SellDashboardStoreRoute
  '/sell/dashboard/': typeof SellDashboardIndexRoute
  '/sell/dashboard/products/$productId': typeof SellDashboardProductsProductIdRoute
  '/sell/dashboard/products/new': typeof SellDashboardProductsNewRoute
  '/sell/dashboard/products/': typeof SellDashboardProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/diu'
    | '/new-arrivals'
    | '/offers'
    | '/orders'
    | '/reset-password'
    | '/wishlist'
    | '/campus/$campusSlug'
    | '/products/$productSlug'
    | '/sell/dashboard'
    | '/sell/login'
    | '/sell/register'
    | '/sell/status'
    | '/stores/$storeSlug'
    | '/products/'
    | '/sell/'
    | '/stores/'
    | '/sell/dashboard/earnings'
    | '/sell/dashboard/orders'
    | '/sell/dashboard/reviews'
    | '/sell/dashboard/store'
    | '/sell/dashboard/'
    | '/sell/dashboard/products/$productId'
    | '/sell/dashboard/products/new'
    | '/sell/dashboard/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/diu'
    | '/new-arrivals'
    | '/offers'
    | '/orders'
    | '/reset-password'
    | '/wishlist'
    | '/campus/$campusSlug'
    | '/products/$productSlug'
    | '/sell/login'
    | '/sell/register'
    | '/sell/status'
    | '/stores/$storeSlug'
    | '/products'
    | '/sell'
    | '/stores'
    | '/sell/dashboard/earnings'
    | '/sell/dashboard/orders'
    | '/sell/dashboard/reviews'
    | '/sell/dashboard/store'
    | '/sell/dashboard'
    | '/sell/dashboard/products/$productId'
    | '/sell/dashboard/products/new'
    | '/sell/dashboard/products'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/diu'
    | '/new-arrivals'
    | '/offers'
    | '/orders'
    | '/reset-password'
    | '/wishlist'
    | '/campus/$campusSlug'
    | '/products/$productSlug'
    | '/sell/dashboard'
    | '/sell/login'
    | '/sell/register'
    | '/sell/status'
    | '/stores/$storeSlug'
    | '/products/'
    | '/sell/'
    | '/stores/'
    | '/sell/dashboard/earnings'
    | '/sell/dashboard/orders'
    | '/sell/dashboard/reviews'
    | '/sell/dashboard/store'
    | '/sell/dashboard/'
    | '/sell/dashboard/products/$productId'
    | '/sell/dashboard/products/new'
    | '/sell/dashboard/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  DiuRoute: typeof DiuRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WishlistRoute: typeof WishlistRoute
  CampusCampusSlugRoute: typeof CampusCampusSlugRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  SellDashboardRoute: typeof SellDashboardRouteWithChildren
  SellLoginRoute: typeof SellLoginRoute
  SellRegisterRoute: typeof SellRegisterRoute
  SellStatusRoute: typeof SellStatusRoute
  StoresStoreSlugRoute: typeof StoresStoreSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SellIndexRoute: typeof SellIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diu': {
      id: '/diu'
      path: '/diu'
      fullPath: '/diu'
      preLoaderRoute: typeof DiuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus/$campusSlug': {
      id: '/campus/$campusSlug'
      path: '/campus/$campusSlug'
      fullPath: '/campus/$campusSlug'
      preLoaderRoute: typeof CampusCampusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/dashboard': {
      id: '/sell/dashboard'
      path: '/sell/dashboard'
      fullPath: '/sell/dashboard'
      preLoaderRoute: typeof SellDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/login': {
      id: '/sell/login'
      path: '/sell/login'
      fullPath: '/sell/login'
      preLoaderRoute: typeof SellLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/register': {
      id: '/sell/register'
      path: '/sell/register'
      fullPath: '/sell/register'
      preLoaderRoute: typeof SellRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/status': {
      id: '/sell/status'
      path: '/sell/status'
      fullPath: '/sell/status'
      preLoaderRoute: typeof SellStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeSlug': {
      id: '/stores/$storeSlug'
      path: '/stores/$storeSlug'
      fullPath: '/stores/$storeSlug'
      preLoaderRoute: typeof StoresStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/dashboard/': {
      id: '/sell/dashboard/'
      path: '/'
      fullPath: '/sell/dashboard/'
      preLoaderRoute: typeof SellDashboardIndexRouteImport
      parentRoute: typeof SellDashboardRoute
    }
    '/sell/dashboard/earnings': {
      id: '/sell/dashboard/earnings'
      path: '/earnings'
      fullPath: '/sell/dashboard/earnings'
      preLoaderRoute: typeof SellDashboardEarningsRouteImport
      parentRoute: typeof SellDashboardRoute
    }
    '/sell/dashboard/orders': {
      id: '/sell/dashboard/orders'
      path: '/orders'
      fullPath: '/sell/dashboard/orders'
      preLoaderRoute: typeof SellDashboardOrdersRouteImport
      parentRoute: typeof SellDashboardRoute
    }
    '/sell/dashboard/reviews': {
      id: '/sell/dashboard/reviews'
      path: '/reviews'
      fullPath: '/sell/dashboard/reviews'
      preLoaderRoute: typeof SellDashboardReviewsRouteImport
      parentRoute: typeof SellDashboardRoute
    }
    '/sell/dashboard/store': {
      id: '/sell/dashboard/store'
      path: '/store'
      fullPath: '/sell/dashboard/store'
      preLoaderRoute: typeof SellDashboardStoreRouteImport
      parentRoute: typeof SellDashboardRoute
    }
    '/sell/dashboard/products/': {
      id: '/sell/dashboard/products/'
      path: '/products'
      fullPath: '/sell/dashboard/products/'
      preLoaderRoute: typeof SellDashboardProductsIndexRouteImport
      parentRoute: typeof SellDashboardRoute
    }
    '/sell/dashboard/products/$productId': {
      id: '/sell/dashboard/products/$productId'
      path: '/products/$productId'
      fullPath: '/sell/dashboard/products/$productId'
      preLoaderRoute: typeof SellDashboardProductsProductIdRouteImport
      parentRoute: typeof SellDashboardRoute
    }
    '/sell/dashboard/products/new': {
      id: '/sell/dashboard/products/new'
      path: '/products/new'
      fullPath: '/sell/dashboard/products/new'
      preLoaderRoute: typeof SellDashboardProductsNewRouteImport
      parentRoute: typeof SellDashboardRoute
    }
  }
}

interface SellDashboardRouteChildren {
  SellDashboardEarningsRoute: typeof SellDashboardEarningsRoute
  SellDashboardOrdersRoute: typeof SellDashboardOrdersRoute
  SellDashboardReviewsRoute: typeof SellDashboardReviewsRoute
  SellDashboardStoreRoute: typeof SellDashboardStoreRoute
  SellDashboardIndexRoute: typeof SellDashboardIndexRoute
  SellDashboardProductsProductIdRoute: typeof SellDashboardProductsProductIdRoute
  SellDashboardProductsNewRoute: typeof SellDashboardProductsNewRoute
  SellDashboardProductsIndexRoute: typeof SellDashboardProductsIndexRoute
}

const SellDashboardRouteChildren: SellDashboardRouteChildren = {
  SellDashboardEarningsRoute: SellDashboardEarningsRoute,
  SellDashboardOrdersRoute: SellDashboardOrdersRoute,
  SellDashboardReviewsRoute: SellDashboardReviewsRoute,
  SellDashboardStoreRoute: SellDashboardStoreRoute,
  SellDashboardIndexRoute: SellDashboardIndexRoute,
  SellDashboardProductsProductIdRoute: SellDashboardProductsProductIdRoute,
  SellDashboardProductsNewRoute: SellDashboardProductsNewRoute,
  SellDashboardProductsIndexRoute: SellDashboardProductsIndexRoute,
}

const SellDashboardRouteWithChildren = SellDashboardRoute._addFileChildren(
  SellDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  DiuRoute: DiuRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WishlistRoute: WishlistRoute,
  CampusCampusSlugRoute: CampusCampusSlugRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  SellDashboardRoute: SellDashboardRouteWithChildren,
  SellLoginRoute: SellLoginRoute,
  SellRegisterRoute: SellRegisterRoute,
  SellStatusRoute: SellStatusRoute,
  StoresStoreSlugRoute: StoresStoreSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SellIndexRoute: SellIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
